djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls') )
]

myapp/urls.py
from django.urls import path
from . import views

from .api import TaskViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register('api/tasks', TaskViewSet, 'tasks')


app_name = 'myapp'
urlpatterns = [
	path('signup', views.signup, name='signup' ),
	path('', views.home, name='home' ),
	path('tasks', views.tasks, name='tasks'),
	path('sigout', views.sigout, name='sigout'),
	path('sigin', views.sigin, name='sigin'),
	path('tasks/create', views.create_task, name='create_task'),
	path('tasks/<int:task_id>', views.task_detail, name='task_detail'),
	path('tasks/<int:task_id>/delet_task', views.delet_task, name='delet_task'),
] + router.urls

myapp/models.py
from django.db import models
from django.contrib.auth.models import User




class Task( models.Model ):
	title = models.CharField( max_length=200 )
	description = models.TextField(blank=True)
	created = models.DateTimeField( auto_now_add=True)
	datecompleted = models.DateTimeField( null=True, blank=True )
	important = models.BooleanField( default=False )
	user = models.ForeignKey( User, on_delete=models.CASCADE )

	def __str__(self):
		return self.title + ' by: ' + self.user.username

myapp/forms.py
from django.forms import ModelForm
from .models import Task

class TaskForm( ModelForm ):
	class Meta:
		model = Task
		fields = ['title','description','important']
    

myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .forms import TaskForm
from .models import Task

def signup( request ):

	if request.method == 'GET':
		return render( request, 'myapp/signup.html', {
			'form': UserCreationForm
			})
	else:
		if request.POST['password1'] == request.POST['password2']:

			try:
				user = User.objects.create_user( 
					username=request.POST['username'],
					password=request.POST['password1'],
					)
				user.save()
				login( request, user)
				return redirect('myapp:tasks')
			except IntegrityError:
				return render( request, 'myapp/signup.html', {
					'form': UserCreationForm,
					'error': 'Usuario ya existente'
				})

		else:
			return render( request, 'myapp/signup.html', {
					'form': UserCreationForm,
					'error': 'Contrasenias no coincidentes'
				})

def home( request ):
	return render( request, 'myapp/home.html')

def tasks( request ):
	tasks = Task.objects.filter( user=request.user )
	return render( request, 'myapp/tasks.html', {
		'tasks': tasks
		})

def sigout( request ):
	logout( request )
	return redirect('myapp:home')

def sigin( request ):

	if request.method == 'GET':
		return render( request, 'myapp/sigin.html', {
			'form': AuthenticationForm
			})
	else:

		user = authenticate( request, 
			username=request.POST['username'], 
			password=request.POST['password'] )

		if user is None:
			return render( request, 'myapp/sigin.html', {
				'form': AuthenticationForm,
				'error': 'Usuario o contrasenia incorrectos'
				})
		else:
			login( request, user)
			return redirect('myapp:tasks')


def create_task( request ):

	if request.method == 'GET':
		return render( request, 'myapp/create_task.html', {
			'form': TaskForm
			})
	else:
		try:
			new_task = TaskForm(request.POST).save( commit=False)
			new_task.user = request.user
			new_task.save()
			return redirect('myapp:tasks')
		except ValueError:
			return render( request, 'myapp/create_task.html', {
				'form': TaskForm,
				'error': 'Ingrese un dato valido'
				})			

def task_detail( request, task_id ):

	task = get_object_or_404( Task, pk=task_id, user=request.user)

	if request.method == 'GET':
		update_task = TaskForm(instance=task)
		return render( request, 'myapp/task_detail.html', {'task':task, 'form':update_task})
	else:
		form = TaskForm(request.POST, instance=task)
		form.save()
		return redirect('myapp:tasks')

def delet_task( request, task_id):

	if request.method == 'GET':
		task = get_object_or_404( Task, pk=task_id, user=request.user)
		task.delete()
		return redirect('myapp:tasks')

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<style>
		header{
			background: skyblue;
		}
	</style>
</head>
<body>	
	<header>
		<h1>Gestion de tareas</h1>
		<ul>
			<li>
				<a href=" {% url 'myapp:home' %}">Home</a>
			</li>


			{% if user.is_authenticated %}
				<li>
					<a href=" {% url 'myapp:sigout' %} ">logout</a>
				</li>
				<li>
					<a href=" {% url 'myapp:tasks' %} ">tareas</a>
				</li>
				<li>
					<a href=" {% url 'myapp:create_task' %} ">crear tarea</a>
				</li>
			{% else %}
				<li>
					<a href=" {% url 'myapp:signup' %} ">Signup</a>
				</li>
				<li>
					<a href=" {% url 'myapp:sigin' %} ">Sigin</a>
				</li>
			{% endif %}


		</ul>
	</header>
	<main>
	{% block content %}
	{% endblock %}		
	</main>


</body>
</html>

myapp/templates/myapp/create_task.html
{% extends "myapp/base.html" %}

{% block content %}
	
	<h2>Lista de tareas</h2>

	{% if error %}
		<h2>{{error}}</h2>
	{% endif %}

	<form method="post" >
		{% csrf_token %}

		{{ form.as_p }}
		<input type="submit" value="Guardar">

	</form>
{% endblock %}

myapp/templates/myapp/home.html
{% extends "myapp/base.html" %}

{% block content %}
	<a href=" {% url 'myapp:signup' %} ">
		<button>Registrase</button>
	</a>
			
{% endblock content %}

myapp/templates/myapp/sigin.html
{% extends "myapp/base.html" %}

{% block content %}

	<h2>Sigin</h2>
	<form action="" method="post">
		{% csrf_token %}

		<h2>{{ error }}</h2>
		{{ form.as_p }}
		<button>
			Sigin
		</button>

	</form>

			
{% endblock content %}

myapp/templates/myapp/signup.html
{% extends "myapp/base.html" %}

{% block content %}

	<h1>Signup</h1>
	<form action="" method="post">
		
{% csrf_token %}	
		
		<h2>{{ error }}</h2>
		{{ form.as_p }}
		<input type="submit" value="Enviar">
	</form>
	

			
{% endblock content %}

myapp/templates/myapp/task_detail.html
{% extends "myapp/base.html" %}

{% block content %}

	<h2>Task detail</h2>
	<h2>{{task.title}}</h2>

	<form method="post">
		{% csrf_token %}

		{{form.as_p}}

		<button>
			Update
		</button>
	</form>

	<form action=" {% url 'myapp:delet_task' task.id %}">
		{% csrf_token %}
		
		<button>eleminar</button>
	</form>
		

	
{% endblock content %}

myapp/templates/myapp/tasks.html
{% extends "myapp/base.html" %}

{% block content %}
	<h2>Se encuentra en tareas</h2>
	<a href=" {% url 'myapp:create_task' %}"><button>Crear tarea</button></a>
	<ul>
	{% for task in tasks %}

		<a href=" {% url 'myapp:task_detail' task.id %}">			
			<li>
				<h3>{{task.title}}</h3>
				<p>{{task.description}}</p>
				<p><strong>{{task.user.username}}</strong></p>
			</li>		
		</a>

	{% endfor %}
	</ul>

	
{% endblock content %}